# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f213a462549506fe201242974760381937951ca12ea3de341bb067314f106a7ccfedd3fcc0236a22285eee5cbf5392c19134828729b0cc27b3378f5b8827950

test:
  secret_key_base: 86b9aa00f657b5f5dd2f7add1b6fcc12173f9a394aba5c9bd268dd9435908e597571c630d3e279ef39ce19b0eb6ce7d0ca1c42f58df27d67f1939ac251256bad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
